[server]
maxUploadSize = 10
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FB7185"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#333333"
